[build]
  publish = "out"
  command = "npm run build"

[template.environment]
  CZ_ORG_ID = "Your Codezero Org ID"
  CZ_ORG_API_KEY = "Your Codezero API Key"
  CZ_SPACE_ID = "The ID of your Codezero Teamspace"
